excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://anhhh11.github.io
title: My blog
tagline: Think about programming
description: All is about describing what we want and apply law to achieve it. Using program languages is one way to describe; and programming is the form of applying law.
paginate: 5
